DROP TABLE IF EXISTS todo_list;
DROP TABLE IF EXISTS user_information;

-- ユーザ情報テーブル
CREATE TABLE user_information
(
	user_id INTEGER primary key generated by default as identity,
	user_name varchar(20),
	user_password varchar(60),
	user_role varchar(20) not null
);

--ToDoリストテーブル
CREATE TABLE todo_list
(
    list_id INTEGER primary key generated by default as identity,
	user_id serial references user_information(user_id) not null,
	contents varchar(30),
	due varchar(10),
	is_complete boolean not null
);